[project]
name = "coherence-analyses"
version = "0.1.0"
description = "Research code on coherence analyses for DAS data"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dascore>=0.1.3",
    "ipykernel>=6.29.5",
    "ipywidgets>=8.1.5",
]
